// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZADjM3MixOFRzLWhs9eoIeK7KYfPg6Nw',
    appId: '1:634781175675:web:5cc131dcb41abc78ea37de',
    messagingSenderId: '634781175675',
    projectId: 'foxl-user',
    authDomain: 'foxl-user.firebaseapp.com',
    storageBucket: 'foxl-user.firebasestorage.app',
    measurementId: 'G-VKNCB19YHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvr_zb_RHJyZKYYL8_XLzHiRNucdYlW50',
    appId: '1:634781175675:android:3b9f76282cc37079ea37de',
    messagingSenderId: '634781175675',
    projectId: 'foxl-user',
    storageBucket: 'foxl-user.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBPpzFtDVInG0t0U5T_d3wGQ4UeiWTQzk',
    appId: '1:634781175675:ios:a21da103c9235db8ea37de',
    messagingSenderId: '634781175675',
    projectId: 'foxl-user',
    storageBucket: 'foxl-user.firebasestorage.app',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBPpzFtDVInG0t0U5T_d3wGQ4UeiWTQzk',
    appId: '1:634781175675:ios:a21da103c9235db8ea37de',
    messagingSenderId: '634781175675',
    projectId: 'foxl-user',
    storageBucket: 'foxl-user.firebasestorage.app',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZADjM3MixOFRzLWhs9eoIeK7KYfPg6Nw',
    appId: '1:634781175675:web:2743bd61a92cf30bea37de',
    messagingSenderId: '634781175675',
    projectId: 'foxl-user',
    authDomain: 'foxl-user.firebaseapp.com',
    storageBucket: 'foxl-user.firebasestorage.app',
    measurementId: 'G-G3HREEEB7E',
  );
}
